import Head from "next/head"
import Footer from '../components/footer'
import DiscoverMenu from "../components/discoveringMenu"

const Blogs = () => {

      return (
        <div className="h-screen bg-green-100 dark:bg-gray-900 w-screen">
        <Head>
          <title>Crypto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


        <DiscoverMenu />
        <div className="pt-20 text-center text-2xl font-bold">
          <h1 >page still in progress</h1>
        </div>

        <Footer />

    </div>
  )
};

export default Blogs;