import Head from "next/head"
import Footer from '../components/footer'
import FullTrending from '../components/FullTrending';
import DiscoverMenu from "../components/discoveringMenu"
import { CryptoState } from "../context/cryptoContext";
import { MenuItem, Select} from '@mui/material'
import { useContext} from "react"

const TrendingFull = () => {
    const { currency, setCurrency } = useContext(CryptoState);

      return (
        <div className="h-screen dark:bg-gray-900 bg-green-100 relative">
            <Head>
            <title>Crypto</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <DiscoverMenu />
            <Select
                  variant="outlined"
                  labelId="demo-simple-select-label"
                  id="demo-simple-select"
                  value={currency}
                  className="text-green-600 border-red-300 hover:text-green-800 dark:dark-color dark:hover:text-gray-400 cursor-pointer absolute right-5 top-3 w-24 h-7 focus:outline-none"
                  onChange={(e) => setCurrency(e.target.value)}
                >
                  <MenuItem value={"USD"}>USD</MenuItem>
                  <MenuItem value={"INR"}>INR</MenuItem> 
                  <MenuItem value={"NGN"}>NGN</MenuItem> 
                </Select>
            <FullTrending />
            <Footer />

        </div>
  )
};

export default TrendingFull;